// <auto-generated />
using System;
using B3.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace B3.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250301194628_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("B3.Domain.Models.DescontoImpostoRenda", b =>
                {
                    b.Property<Guid>("IdDescontoImpostoRenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("QtdeMesesFim")
                        .HasColumnType("int");

                    b.Property<int>("QtdeMesesInicio")
                        .HasColumnType("int");

                    b.HasKey("IdDescontoImpostoRenda");

                    b.ToTable("DescontoImpostoRenda", (string)null);
                });

            modelBuilder.Entity("B3.Domain.Models.Indexador", b =>
                {
                    b.Property<int>("IdIndexador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdIndiceTipo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIndexador"), 1L, 1);

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TaxaAtual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdIndexador");

                    b.ToTable("IndiceTipo", (string)null);
                });

            modelBuilder.Entity("B3.Domain.Models.TipoTitulo", b =>
                {
                    b.Property<int>("IdTipoTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTitulo"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RendaFixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdTipoTitulo");

                    b.ToTable("TituloTipo", (string)null);
                });

            modelBuilder.Entity("B3.Domain.Models.Titulo", b =>
                {
                    b.Property<Guid>("IdTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdIndexador")
                        .HasColumnType("int")
                        .HasColumnName("IdIndiceTipo");

                    b.Property<int>("IdTipoTitulo")
                        .HasColumnType("int");

                    b.Property<string>("NomeTitulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("PosFixado")
                        .HasColumnType("bit");

                    b.Property<decimal>("TaxaRendimento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTitulo");

                    b.HasIndex("IdIndexador");

                    b.HasIndex("IdTipoTitulo");

                    b.ToTable("Titulo", (string)null);
                });

            modelBuilder.Entity("B3.Domain.Models.Titulo", b =>
                {
                    b.HasOne("B3.Domain.Models.Indexador", "Indexador")
                        .WithMany("Titulos")
                        .HasForeignKey("IdIndexador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("B3.Domain.Models.TipoTitulo", "TipoTitulo")
                        .WithMany("Titulos")
                        .HasForeignKey("IdTipoTitulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indexador");

                    b.Navigation("TipoTitulo");
                });

            modelBuilder.Entity("B3.Domain.Models.Indexador", b =>
                {
                    b.Navigation("Titulos");
                });

            modelBuilder.Entity("B3.Domain.Models.TipoTitulo", b =>
                {
                    b.Navigation("Titulos");
                });
#pragma warning restore 612, 618
        }
    }
}
